name: Llamar Workflow Reusable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  llamar-workflow-externo:
    uses: Thecode42/platform-dummy/.github/workflows/reusable.yml@master
    with:
      ambiente: production
      mensaje: "Desplegando desde mi-proyecto"